# Schema for Geocoder module.

gecoder.settings:
  type: config_object
  label: 'Geocoder settings'
  mapping:
    cache:
      type: boolean
      label: 'Cache results'
    plugins_options:
      type: string
      label: 'Geocoders plugins Specific Options'
